# Generated by Django 3.0.8 on 2020-08-12 08:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Street address')),
                ('street_address2', models.CharField(blank=True, max_length=255, verbose_name='Street address (2nd line)')),
                ('postal_code', models.CharField(blank=True, max_length=255, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('country', models.CharField(blank=True, choices=[], max_length=255, verbose_name='Country')),
                ('geoposition', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
