# Generated by Django 3.0.8 on 2020-08-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('UK', 'United Kingdom'), ('CN', 'China')], max_length=255, verbose_name='Country'),
        ),
    ]
