# Generated by Django 3.0.8 on 2020-08-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='Rating'),
        ),
    ]
